package dev.lunarcoffee.risako.bot.consts

object Emoji {
    const val PING_PONG = "\uD83C\uDFD3"
    const val OPEN_FILE_FOLDER = "\uD83D\uDCC2"
    const val RADIO_BUTTON = "\uD83D\uDD18"
    const val PAGE_FACING_UP = "\uD83D\uDCC4"
    const val GAME_DIE = "\uD83C\uDFB2"
    const val THINKING = "\uD83E\uDD14"
    const val BILLIARD_BALL = "\uD83C\uDFB1"
    const val MAG_GLASS = "\uD83D\uDD0D"
    const val LAPTOP_COMPUTER = "\uD83D\uDCBB"
    const val FRAMED_PICTURE = "\uD83D\uDDBC️"
    const val COFFEE = "\u2615"
    const val SATELLITE = "\uD83D\uDEF0️"
    const val INDICATOR_A = "\uD83C\uDDE6"
    const val INDICATOR_F = "\uD83C\uDDEB"
    const val INDICATOR_X = "\uD83C\uDDFD"
    const val HAMMER_AND_WRENCH = "\uD83D\uDEE0️"
    const val SCALES = "\u2696"
    const val ALARM_CLOCK = "\u23F0"
    const val MUTE = "\uD83D\uDD07"
    const val COMPUTER_MOUSE = "\uD83D\uDDB1️"
    const val DRUM = "\uD83E\uDD41"
    const val PINEAPPLE = "\uD83C\uDF4D"
    const val MUSICAL_KEYBOARD = "\uD83C\uDFB9"
    const val WORLD_MAP = "\uD83D\uDDFA️"
    const val WHITE_SQUARE_BUTTON = "\uD83D\uDD33"
    const val SNOW_CAPPED_MOUNTAIN = "\uD83C\uDFD4"
    const val OPEN_BOOK = "\uD83D\uDCD6"
    const val BOOKMARK = "\uD83D\uDD16"
    const val SPY = "\uD83D\uDD75"
    const val EXPLODE = "\uD83D\uDCA5"
    const val CHART_UPWARDS_TREND = "\uD83D\uDCC8"
    const val STAR = "\u2B50"
}
